"use client";

import { useState, useEffect, Suspense } from "react";
import { motion } from "framer-motion";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import {
  CheckCircle,
  Package,
  Truck,
  MapPin,
  Calendar,
  Copy,
  Download,
  Eye,
  Loader2,
  ArrowRight,
  DollarSign,
  RefreshCw,
  AlertCircle,
} from "lucide-react";
import toast from "react-hot-toast";
import { api } from "@/lib/api";
import { useAppSelector } from "@/store/hooks";

function ConfirmationContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { isAuthenticated } = useAppSelector((state) => state.auth);
  const [shipment, setShipment] = useState(null);
  const [loading, setLoading] = useState(true);
  const [labelUrl, setLabelUrl] = useState(null);
  const [trackingNumber, setTrackingNumber] = useState(null);
  const [copied, setCopied] = useState(false);
  const [labelError, setLabelError] = useState(null);
  const [labelGenerating, setLabelGenerating] = useState(false);

  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/login");
      return;
    }

    const sessionId = searchParams.get("session_id");
    if (!sessionId) {
      // Try to get shipment from sessionStorage
      const storedShipment = sessionStorage.getItem("shipmentData");
      if (storedShipment) {
        const data = JSON.parse(storedShipment);
        setShipment(data);
        setTrackingNumber(data.tracking_number || data.shipment_number);
        setLoading(false);
      } else {
        toast.error("No shipment found");
        router.push("/quote");
      }
      return;
    }

    // Payment was successful, fetch shipment details
    fetchShipmentDetails(sessionId);
  }, [isAuthenticated, router, searchParams]);

  const fetchShipmentDetails = async (sessionId) => {
    try {
      // Get shipment_id from sessionStorage or payment metadata
      const storedShipment = sessionStorage.getItem("shipmentData");
      let shipmentId = null;

      if (storedShipment) {
        const data = JSON.parse(storedShipment);
        shipmentId = data.id || data.shipment_id;

        // Check if this is a buy_and_ship quote payment from stored data
        if (
          data.source_type === "buy_and_ship" ||
          data.payment_type === "buy_and_ship_quote"
        ) {
          // If we have shipment ID, redirect to detail page
          if (data.id || data.shipment_id) {
            setTimeout(() => {
              router.push(
                `/dashboard/shipments/${data.id || data.shipment_id}`
              );
            }, 2000);
            return;
          }
        }
      }

      if (shipmentId) {
        // Fetch latest shipment data (label should be generated by webhook)
        const API_URL =
          process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
        const response = await fetch(
          `${API_URL}/api/v1/logistics/shipments/${shipmentId}/`,
          {
            headers: {
              Authorization: `Bearer ${localStorage.getItem("access_token")}`,
            },
          }
        );

        if (response.ok) {
          const data = await response.json();
          setShipment(data);
          setLabelUrl(data.easyship_label_url || null);
          setTrackingNumber(
            data.tracking_number ||
              data.local_carrier_tracking_number ||
              data.shipment_number
          );

          // If this is a buy_and_ship quote payment, redirect to shipment detail page
          if (data.source_type === "buy_and_ship") {
            // Redirect to shipment detail page
            setTimeout(() => {
              router.push(`/dashboard/shipments/${data.id}`);
            }, 2000); // Show success message for 2 seconds then redirect
            return;
          }
        } else {
          // Fallback to stored data
          if (storedShipment) {
            const data = JSON.parse(storedShipment);
            setShipment(data);
            setTrackingNumber(data.tracking_number || data.shipment_number);
            setLabelUrl(data.easyship_label_url || null);
          }
        }
      } else if (storedShipment) {
        const data = JSON.parse(storedShipment);
        setShipment(data);
        setTrackingNumber(data.tracking_number || data.shipment_number);
      }
    } catch (err) {
      toast.error("Failed to load shipment details");
    } finally {
      setLoading(false);
    }
  };

  const generateLabel = async (shipmentId) => {
    // Check if label is already generating
    if (shipment?.status === "label_generating") {
      toast.error("Label generation is already in progress. Please wait.");
      return;
    }

    // Check if label already exists
    if (shipment?.easyship_label_url) {
      toast.error("Label has already been generated for this shipment.");
      return;
    }

    setLabelGenerating(true);
    setLabelError(null);
    try {
      const response = await api.post(
        `/logistics/shipments/${shipmentId}/generate-label/`,
        {}
      );

      const data = response.data;
      setLabelUrl(data.label_url);
      setTrackingNumber(data.tracking_number);
      setShipment((prev) => ({
        ...prev,
        tracking_number: data.tracking_number,
        easyship_label_url: data.label_url,
        status: data.shipment?.status || prev.status, // Update status from response
      }));
      setLabelError(null);
      toast.success(
        "Label generation started! You'll be notified when it's ready."
      );
    } catch (err) {
      const errorMessage =
        err.response?.data?.error ||
        err.message ||
        "Failed to generate label. Please try again.";
      setLabelError(errorMessage);
      toast.error(errorMessage);
      console.error("Failed to generate label:", err);
    } finally {
      setLabelGenerating(false);
    }
  };

  const copyTrackingNumber = () => {
    if (trackingNumber) {
      navigator.clipboard.writeText(trackingNumber);
      setCopied(true);
      toast.success("Tracking number copied!");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
      </div>
    );
  }

  if (!shipment) {
    return null;
  }

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-red-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 pt-24 pb-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Success Header */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="text-center mb-12"
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: "spring", bounce: 0.4 }}
              className="inline-flex p-6 rounded-full bg-green-100 dark:bg-green-900/30 mb-6"
            >
              <CheckCircle className="w-16 h-16 text-green-500" />
            </motion.div>
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-black mb-4">
              <span className="bg-gradient-to-r from-green-600 via-emerald-500 to-green-500 bg-clip-text text-transparent">
                Payment Successful!
              </span>
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-400">
              Your shipment has been created successfully
            </p>
          </motion.div>

          {/* Shipment Details Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="card-modern p-8 bg-white dark:bg-gray-800 border-2 border-green-200 dark:border-green-800 mb-8"
          >
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-3xl font-black text-gray-900 dark:text-white">
                Shipment Details
              </h2>
              <span className="px-4 py-2 rounded-full bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 font-bold">
                {shipment.status?.replace("_", " ").toUpperCase()}
              </span>
            </div>

            <div className="grid md:grid-cols-2 gap-6 mb-6">
              <div className="flex items-center gap-4 p-4 rounded-xl bg-orange-50 dark:bg-orange-900/20">
                <div className="p-3 rounded-lg bg-orange-500">
                  <Package className="w-6 h-6 text-white" />
                </div>
                <div>
                  <div className="text-sm font-semibold text-gray-500 uppercase">
                    Shipment Number
                  </div>
                  <div className="text-lg font-bold text-gray-900 dark:text-white">
                    {shipment.shipment_number}
                  </div>
                </div>
              </div>

              {trackingNumber && (
                <div className="flex items-center gap-4 p-4 rounded-xl bg-blue-50 dark:bg-blue-900/20">
                  <div className="p-3 rounded-lg bg-blue-500">
                    <Truck className="w-6 h-6 text-white" />
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-semibold text-gray-500 uppercase">
                      Tracking Number
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="text-lg font-bold text-gray-900 dark:text-white">
                        {trackingNumber}
                      </div>
                      <button
                        onClick={copyTrackingNumber}
                        className="p-1 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
                      >
                        <Copy className="w-4 h-4 text-gray-500" />
                      </button>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex items-center gap-4 p-4 rounded-xl bg-purple-50 dark:bg-purple-900/20">
                <div className="p-3 rounded-lg bg-purple-500">
                  <DollarSign className="w-6 h-6 text-white" />
                </div>
                <div>
                  <div className="text-sm font-semibold text-gray-500 uppercase">
                    Total Paid
                  </div>
                  <div className="text-lg font-bold text-gray-900 dark:text-white">
                    ${parseFloat(shipment.total_cost).toFixed(2)}
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-4 p-4 rounded-xl bg-green-50 dark:bg-green-900/20">
                <div className="p-3 rounded-lg bg-green-500">
                  <Calendar className="w-6 h-6 text-white" />
                </div>
                <div>
                  <div className="text-sm font-semibold text-gray-500 uppercase">
                    Created
                  </div>
                  <div className="text-lg font-bold text-gray-900 dark:text-white">
                    {new Date(shipment.created_at).toLocaleDateString()}
                  </div>
                </div>
              </div>
            </div>

            {/* Addresses */}
            <div className="grid md:grid-cols-2 gap-6 mb-6 pt-6 border-t-2 border-gray-200 dark:border-gray-700">
              <div>
                <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                  <MapPin className="w-5 h-5 text-orange-500" />
                  Origin
                </h3>
                <div className="text-sm text-gray-600 dark:text-gray-400 space-y-1">
                  <div className="font-semibold text-gray-900 dark:text-white">
                    {shipment.origin_address?.full_name}
                  </div>
                  <div>{shipment.origin_address?.street_address}</div>
                  {shipment.origin_address?.street_address_2 && (
                    <div>{shipment.origin_address.street_address_2}</div>
                  )}
                  <div>
                    {shipment.origin_address?.city},{" "}
                    {shipment.origin_address?.state_province}{" "}
                    {shipment.origin_address?.postal_code}
                  </div>
                  <div>{shipment.origin_address?.country}</div>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                  <MapPin className="w-5 h-5 text-blue-500" />
                  Destination
                </h3>
                <div className="text-sm text-gray-600 dark:text-gray-400 space-y-1">
                  <div className="font-semibold text-gray-900 dark:text-white">
                    {shipment.destination_address?.full_name}
                  </div>
                  <div>{shipment.destination_address?.street_address}</div>
                  {shipment.destination_address?.street_address_2 && (
                    <div>{shipment.destination_address.street_address_2}</div>
                  )}
                  <div>
                    {shipment.destination_address?.city},{" "}
                    {shipment.destination_address?.state_province}{" "}
                    {shipment.destination_address?.postal_code}
                  </div>
                  <div>{shipment.destination_address?.country}</div>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-wrap gap-4 pt-6 border-t-2 border-gray-200 dark:border-gray-700">
              {/* For buy_and_ship quotes, redirect to shipment detail page instead of showing label generation */}
              {shipment?.source_type === "buy_and_ship" ? (
                <Link
                  href={`/dashboard/shipments/${shipment.id}`}
                  className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-600 to-red-500 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all"
                >
                  <Eye className="w-5 h-5" />
                  View Shipment Details
                  <ArrowRight className="w-5 h-5" />
                </Link>
              ) : (
                <>
                  {labelUrl && (
                    <motion.a
                      href={labelUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-600 to-red-500 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all"
                    >
                      <Download className="w-5 h-5" />
                      Download Label
                    </motion.a>
                  )}

                  {!labelUrl &&
                    !labelError &&
                    !labelGenerating &&
                    shipment &&
                    (shipment.status === "payment_received" ||
                      shipment.status === "quote_approved") && (
                      <button
                        onClick={() =>
                          generateLabel(shipment.id || shipment.shipment_id)
                        }
                        disabled={labelGenerating}
                        className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-600 to-red-500 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all disabled:opacity-50"
                      >
                        {labelGenerating ? (
                          <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            Generating Label...
                          </>
                        ) : (
                          <>
                            <Download className="w-5 h-5" />
                            Generate Label
                          </>
                        )}
                      </button>
                    )}
                </>
              )}

              {!labelUrl && labelGenerating && !labelError && (
                <div className="flex items-center gap-2 px-6 py-3 bg-yellow-50 dark:bg-yellow-900/20 border-2 border-yellow-200 dark:border-yellow-800 rounded-xl">
                  <Loader2 className="w-5 h-5 animate-spin text-yellow-600 dark:text-yellow-400" />
                  <span className="text-yellow-800 dark:text-yellow-200 font-semibold">
                    Generating label...
                  </span>
                </div>
              )}

              {labelError && (
                <div className="w-full p-4 bg-red-50 dark:bg-red-900/20 border-2 border-red-200 dark:border-red-800 rounded-xl">
                  <div className="flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <h4 className="text-red-800 dark:text-red-200 font-bold mb-1">
                        Label Generation Failed
                      </h4>
                      <p className="text-red-700 dark:text-red-300 text-sm mb-3">
                        {labelError}
                      </p>
                      <button
                        onClick={() =>
                          generateLabel(shipment.id || shipment.shipment_id)
                        }
                        disabled={labelGenerating}
                        className="flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 disabled:bg-red-400 text-white rounded-lg font-semibold transition-all"
                      >
                        {labelGenerating ? (
                          <>
                            <Loader2 className="w-4 h-4 animate-spin" />
                            Retrying...
                          </>
                        ) : (
                          <>
                            <RefreshCw className="w-4 h-4" />
                            Retry Label Generation
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {trackingNumber && (
                <Link
                  href={`/track/${trackingNumber}`}
                  className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-500 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all"
                >
                  <Eye className="w-5 h-5" />
                  Track Shipment
                </Link>
              )}

              <Link
                href="/dashboard"
                className="flex items-center gap-2 px-6 py-3 bg-white dark:bg-gray-700 border-2 border-gray-200 dark:border-gray-600 text-gray-900 dark:text-white rounded-xl font-bold hover:bg-gray-50 dark:hover:bg-gray-600 transition-all"
              >
                Go to Dashboard
                <ArrowRight className="w-5 h-5" />
              </Link>
            </div>
          </motion.div>

          {/* Next Steps */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="card-modern p-6 bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-800"
          >
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
              What's Next?
            </h3>
            <ul className="space-y-2 text-gray-600 dark:text-gray-400">
              {shipment?.pickup_cost > 0 ? (
                <>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span>
                      Pickup has been scheduled. Our team will contact you to
                      arrange pickup time.
                    </span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span>
                      You'll receive a pickup confirmation email with details.
                    </span>
                  </li>
                </>
              ) : (
                <>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span>
                      {labelUrl
                        ? "Download and print your shipping label"
                        : "Your shipping label will be generated shortly"}
                    </span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span>
                      {shipment?.is_local_shipping
                        ? "Attach the label to your package and drop it off at the carrier location (e.g., USPS)"
                        : "Attach the label to your package and drop it off at the carrier location"}
                    </span>
                  </li>
                </>
              )}
              <li className="flex items-start gap-2">
                <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
                <span>
                  Track your shipment using the tracking number provided
                </span>
              </li>
            </ul>
          </motion.div>
        </div>
      </div>
      <Footer />
    </>
  );
}

export default function ConfirmationPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-orange-50 via-white to-red-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
          <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
        </div>
      }
    >
      <ConfirmationContent />
    </Suspense>
  );
}
